/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBranchButton: typeof import('./src/components/nodes/RouteNode/AddBranchButton.vue')['default']
    AddButton: typeof import('./src/components/nodes/AddButton/index.vue')['default']
    ApprovalNodeSteps: typeof import('./src/components/Steps/ApprovalNodeSteps.vue')['default']
    ApproverSetters: typeof import('./src/components/Setters/ApproverSetters.vue')['default']
    AuditSetters: typeof import('./src/components/Setters/AuditSetters.vue')['default']
    BaseForm: typeof import('./src/components/BasicInformation/BaseForm.vue')['default']
    BasicInformation: typeof import('./src/components/BasicInformation/index.vue')['default']
    BranchNode: typeof import('./src/components/nodes/RouteNode/BranchNode.vue')['default']
    CardTable: typeof import('./src/components/CardTable/index.vue')['default']
    CardTitle: typeof import('./src/components/CardTitle/index.vue')['default']
    ChildNode: typeof import('./src/components/nodes/ChildNode.vue')['default']
    CloseButton: typeof import('./src/components/nodes/CloseButton.vue')['default']
    ConditionButtons: typeof import('./src/components/nodes/RouteNode/ConditionButtons.vue')['default']
    ConditionNodeTitle: typeof import('./src/components/nodes/RouteNode/ConditionNodeTitle.vue')['default']
    ConditionPriority: typeof import('./src/components/nodes/RouteNode/ConditionPriority.vue')['default']
    ConditionSetters: typeof import('./src/components/Setters/ConditionSetters.vue')['default']
    ContentPanel: typeof import('./src/components/nodes/AddButton/ContentPanel.vue')['default']
    EndNode: typeof import('./src/components/nodes/EndNode.vue')['default']
    ErrorTip: typeof import('./src/components/nodes/ErrorTip.vue')['default']
    Footer: typeof import('./src/components/SettingsPanel/Footer.vue')['default']
    MaterialItem: typeof import('./src/components/nodes/AddButton/MaterialItem.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    NodeTitle: typeof import('./src/components/nodes/NodeTitle.vue')['default']
    NodeTitleEditor: typeof import('./src/components/SettingsPanel/NodeTitleEditor.vue')['default']
    NormalNode: typeof import('./src/components/nodes/NormalNode.vue')['default']
    NotifierSetters: typeof import('./src/components/Setters/NotifierSetters.vue')['default']
    OperationBar: typeof import('./src/components/OperationBar/index.vue')['default']
    OpHisSteps: typeof import('./src/components/Steps/OpHisSteps.vue')['default']
    Report: typeof import('./src/components/Report/index.vue')['default']
    ReportView: typeof import('./src/components/ReportView/index.vue')['default']
    RightArrow: typeof import('./src/components/icons/RightArrow.vue')['default']
    RouteNode: typeof import('./src/components/nodes/RouteNode/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingNodeTitle: typeof import('./src/components/SettingsPanel/SettingNodeTitle.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel/index.vue')['default']
    StartNode: typeof import('./src/components/nodes/StartNode.vue')['default']
    WorkflowEditor: typeof import('./src/components/WorkflowEditor/index.vue')['default']
    ZoomBar: typeof import('./src/components/ZoomBar/index.vue')['default']
  }
}
